services:
  database:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - database_volume:/postgres/data/
  app:
    build: .
    container_name: app
    env_file:
      - .env
    ports:
      - 5000:5000
     
volumes:
  database_volume: